### ISSUE TITLE
Question about Milestone 6

### ISSUE THREAD

**Issue by Farnaz1234** [STAT547-UBC-2019-20/group_13#35] opened 2020-04-07 16:24 UTC
Hi @yuliaUU, @andrealee011, @matthewconnell 

For deploying our app to heroku as part of milestone 6, I followed the instructions on cm111 to step  8, where it says commit and push your files. In this step when I write git commit in Rstudio terminal it says your branch is up to date and working tree is clean. I am in the very last step for deploying our app to heroku, but I don’t know how to commit and push. Would you please help me with this?

I really appreciate your help in advance!

Thanks,
Farnaz

**Comment by matthewconnell** [comment] 2020-04-07 16:52
Hi!

Did you `git add .` first? If not what does it say when you type `git status`?

**Comment by racquellem** [comment] 2020-04-07 17:02
Hi Matthew,

I am also having the same problem. When I type 'git status' it shows:

````
Racquelles-MacBook-Air:deployed_class_app racquellemangahas$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
````

Thanks,
Racquelle

**Comment by Farnaz1234** [comment] 2020-04-07 17:08
Thanks so much @matthewconnell 

When I write git add . nothing appears. When I write git commit it says:
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean

And when I write git status it shows:
On branch master
Your branch is up to date with 'origin/master'.
nothing to commit, working tree clean

Thanks,
Farnaz

**Comment by Farnaz1234** [comment] 2020-04-07 17:17
Yes, I added 5 files (all required files except Procfile which I wasn't able to find) locally in a folder on my desktop. When I type ls in the terminal it shows:
README.md  app.R  dash_components.R  dash_functions.R

**Comment by racquellem** [comment] 2020-04-07 17:18
I downloaded the 5 files as a zip from the repository and then transferred it to my 'temporary' folder on my desktop, so it automatically got added on Github.

When I type `ls` it also only shows me:

```
Racquelles-MacBook-Air:deployed_class_app racquellemangahas$ ls

README.md               app.R                   dash_components.R       dash_functions.R
```

**Comment by matthewconnell** [comment] 2020-04-07 17:24
Okay, so it looks like the five files from [here](https://github.com/STAT547-UBC-2019-20/dashR_heroku_deploy) aren't in the folder. So you want those files (Dockerfile, app.json, apt-packages, heroku.yml, and init.R) in your `deployed_class_app` folder (which I believe is *in* your `tmp` folder).  You should be able to click and drag them from wherever they are. Let me know if it works!

-Matthew

**Comment by racquellem** [comment] 2020-04-07 17:45
Hi Matthew,

I moved the files to the `deployed_class_app` folder as shown below:
````
Racquelles-MacBook-Air:deployed_class_app racquellemangahas$ git add .
Racquelles-MacBook-Air:deployed_class_app racquellemangahas$ git commit -m "added required files TO the dashdeployed class app folder"
[master e87321f] added required files TO the dashdeployed class app folder
 5 files changed, 48 insertions(+)
 create mode 100755 Dockerfile
 create mode 100755 app.json
 create mode 100755 apt-packages
 create mode 100755 heroku.yml
 create mode 100755 init.R
Racquelles-MacBook-Air:deployed_class_app racquellemangahas$ git status
On branch master
Your branch is ahead of 'origin/master' by 1 commit.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
Racquelles-MacBook-Air:deployed_class_app racquellemangahas$ git push
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 4 threads
Compressing objects: 100% (5/5), done.
Writing objects: 100% (7/7), 1.42 KiB | 1.42 MiB/s, done.
Total 7 (delta 0), reused 0 (delta 0)
To https://github.com/racquellem/deployed_class_app.git
   96c923e..e87321f  master -> master
Racquelles-MacBook-Air:deployed_class_app racquellemangahas$ git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
````

But then when I go to the heroku to manually deploy a GitHub branch it still gives me this error message: 
![Screen Shot 2020-04-07 at 1 40 38 PM](https://user-images.githubusercontent.com/54858652/78701674-6a006780-78d5-11ea-80fd-ab6c3996ca20.png)

Previously, heroku told me to do this:
````
Racquelles-MacBook-Air:deployed_class_app racquellemangahas$ heroku stack:set heroku-18
Setting stack to heroku-18... done
````

And on my `deploy_class_app` folder on GitHub, it repeatedly tells me that my branch is ahead by 1 commit, but then whenever I create a pull request, it says "This branch has no conflicts with the base branch".

Do you know what I should do?

Thanks!!
Racquelle

**Comment by matthewconnell** [comment] 2020-04-07 18:08
Hmm, how long did it take to give you that error? Immediately? A few minutes?

**Comment by racquellem** [comment] 2020-04-07 18:11
As soon as I pressed the 'Deploy Branch' is gave me that error immediately

**Comment by racquellem** [comment] 2020-04-07 18:16
Also, I just realized that it says my branch is 1 commit ahead because it is referring to the actual STAT547-UBC-2019-20/deployed_class_app!

**Comment by yuliaUU** [comment] 2020-04-07 18:28
did you link to the forked repo in your GitHub ?

**Comment by yuliaUU** [comment] 2020-04-07 18:30
also, are you working with master brunch is your R project or yo created a brunch? caus then you will need to merge your branch into the master

**Comment by racquellem** [comment] 2020-04-07 19:58
Hi @yuliaUU and @matthewconnell,

Thanks for the help! I was eventually able to get it to work. I will let you know if I have anymore questions.

**Comment by matthewconnell** [comment] 2020-04-07 19:59
Great! Can you share what the solution was in case anyone else comes across a similar issue?

**Comment by racquellem** [comment] 2020-04-08 00:18
Hi @matthewconnell,

Farnaz and I were able to deploy the app on heroku, although this was through my branch `racquellem/group-13-1` because our `STAT547-UBC-2019-20/group_13` is severely conflicted and we have trouble fixing it. However, it shows this error message after my app was successfully deployed:

![Screen Shot 2020-04-07 at 8 10 56 PM](https://user-images.githubusercontent.com/54858652/78731076-a4392b80-790c-11ea-8e7b-d61eff927371.png)

And when I do what they suggested by checking my log details in Rstudio, it gives me:

```
Racquelles-MacBook-Air:group_13 racquellemangahas$ heroku logs --tail
 ▸    You do not have access to the app group13suicides.
```

Any help is appreciated, and apologies for asking such a last minute question!

Thanks,
Racquelle

**Comment by yuliaUU** [comment] 2020-04-08 04:31
are you in correct working directory?

**Comment by yuliaUU** [comment] 2020-04-08 04:36
this may occur because I was mixing the name of Heroku Apps with the name of git remotes. So when I was calling `heroku logs --app <name of the app>`

**Comment by yuliaUU** [comment] 2020-04-08 04:41
also, try and redo steps 25.3.2.6

**Comment by yuliaUU** [comment] 2020-04-08 04:46
Heroku create command should be run in terminal only after you changed to directory where all the files are ( app. R and 5 files). those needs to be put in the main project directory ( where ll the folders are)

**Comment by racquellem** [comment] 2020-04-08 14:59
Hi Yulia!

It doesn't allow me to use another fork since I already forked it the repository at the beginning? I also added the necessary `install.packages()` in the `init.R`.

I redid the steps from [25.3.2.6 Deploy your app to heroku](
https://stat545guidebook.netlify.com/deploying-your-dashboards-on-heroku.html), but I skipped the step below, as I already had the 5 files in `STAT547-UBC-2019-20/group_13`[(link)](https://github.com/STAT547-UBC-2019-20/group_13):

> 8. **NEW** Next you need to add 5 files from today’s repl.it OR from here to this repository, commit, and push it`

This is the code I had in my terminal:

```
Racquelles-MacBook-Air:group_13-1 racquellemangahas$ cd ~/Desktop/TMPRY
Racquelles-MacBook-Air:TMPRY racquellemangahas$ git clone https://github.com/STAT547-UBC-2019-20/group_13.git
Cloning into 'group_13'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 367 (delta 10), reused 6 (delta 1), pack-reused 338
Receiving objects: 100% (367/367), 8.95 MiB | 4.20 MiB/s, done.
Resolving deltas: 100% (178/178), done.
Racquelles-MacBook-Air:TMPRY racquellemangahas$ cd group_13
Racquelles-MacBook-Air:group_13 racquellemangahas$ heroku create group13suicide --stack container
Creating ⬢ group13suicide... !
 ▸    You've reached the limit of 5 apps for unverified accounts. Delete some apps or add a credit card to verify your account.
Racquelles-MacBook-Air:group_13 racquellemangahas$ heroku create suicidesgroup13 --stack container
Creating ⬢ suicidesgroup13... done, stack is container
https://suicidesgroup13.herokuapp.com/ | https://git.heroku.com/suicidesgroup13.git
```
Once I deployed manually on heroku, it still gave me the webpage application error, so I typed their requested `heroku logs --tail` into my terminal and it gave me:

```
Racquelles-MacBook-Air:group_13 racquellemangahas$ heroku logs --tail
2020-04-08T13:38:17.986765+00:00 app[web.1]: +   )
2020-04-08T13:38:17.986796+00:00 app[web.1]: + )
2020-04-08T13:38:17.987111+00:00 app[web.1]: >
2020-04-08T13:38:17.987113+00:00 app[web.1]: > div_header2 = htmlDiv(
2020-04-08T13:38:17.987136+00:00 app[web.1]: +   list(desc_usage
2020-04-08T13:38:17.987153+00:00 app[web.1]: +   ),
2020-04-08T13:38:17.987171+00:00 app[web.1]: +   style = list(
2020-04-08T13:38:17.987190+00:00 app[web.1]: +     backgroundColor = '#F5F5F5',
2020-04-08T13:38:17.987215+00:00 app[web.1]: +     textAlign = 'center',
2020-04-08T13:38:17.987245+00:00 app[web.1]: +     color = 'black',
2020-04-08T13:38:17.987273+00:00 app[web.1]: +     margin = 2,
2020-04-08T13:38:17.987296+00:00 app[web.1]: +     marginTop = 0
2020-04-08T13:38:17.987327+00:00 app[web.1]: +   )
2020-04-08T13:38:17.987356+00:00 app[web.1]: + )
2020-04-08T13:38:17.987483+00:00 app[web.1]: >
2020-04-08T13:38:17.987485+00:00 app[web.1]: >
2020-04-08T13:38:17.987489+00:00 app[web.1]: > # Side bar with dropdowns
2020-04-08T13:38:17.987503+00:00 app[web.1]: > div_siderbar = htmlDiv(
2020-04-08T13:38:17.987524+00:00 app[web.1]: +   list(image1,
2020-04-08T13:38:17.987541+00:00 app[web.1]: +        Dropdown,
2020-04-08T13:38:17.987560+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.987584+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.987603+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.987625+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.987650+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.987676+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.987702+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.987730+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.987760+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.987792+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.987824+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.987859+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.987894+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.987932+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.987970+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.988011+00:00 app[web.1]: +        image2,
2020-04-08T13:38:17.988052+00:00 app[web.1]: +        Dropdown1
2020-04-08T13:38:17.988117+00:00 app[web.1]: +   ),
2020-04-08T13:38:17.988165+00:00 app[web.1]: +   style = list('background-color' = '#FFEBEE',
2020-04-08T13:38:17.988214+00:00 app[web.1]: +                'textAlign'='center',
2020-04-08T13:38:17.988266+00:00 app[web.1]: +                'color'= 'black',
2020-04-08T13:38:17.988320+00:00 app[web.1]: +                'padding' = '15',
2020-04-08T13:38:17.988377+00:00 app[web.1]: +                'flex-basis' = '17%')
2020-04-08T13:38:17.988517+00:00 app[web.1]: + )
2020-04-08T13:38:17.989494+00:00 app[web.1]: >
2020-04-08T13:38:17.989497+00:00 app[web.1]: > # Plots
2020-04-08T13:38:17.989498+00:00 app[web.1]: > div_main <- htmlDiv(
2020-04-08T13:38:17.989519+00:00 app[web.1]: +   list(dccGraph(id='Violin', figure = make_plot1()),
2020-04-08T13:38:17.989544+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.989568+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.989592+00:00 app[web.1]: +        dccGraph(id='Boxplot', figure = make_plot2()),
2020-04-08T13:38:17.989646+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.989649+00:00 app[web.1]: +        htmlBr(),
2020-04-08T13:38:17.989686+00:00 app[web.1]: +        dccGraph(id='Scatter', figure = make_plot3())
2020-04-08T13:38:17.989729+00:00 app[web.1]: +   )
2020-04-08T13:38:17.989767+00:00 app[web.1]: + )
2020-04-08T13:38:18.676666+00:00 app[web.1]: >
2020-04-08T13:38:18.676685+00:00 app[web.1]: > ## APP LAYOUT
2020-04-08T13:38:18.676685+00:00 app[web.1]: > app$layout(
2020-04-08T13:38:18.676689+00:00 app[web.1]: +   div_header1,
2020-04-08T13:38:18.676729+00:00 app[web.1]: +   div_header2,
2020-04-08T13:38:18.676758+00:00 app[web.1]: +   htmlDiv(
2020-04-08T13:38:18.676793+00:00 app[web.1]: +     list(
2020-04-08T13:38:18.676829+00:00 app[web.1]: +       div_siderbar,
2020-04-08T13:38:18.676866+00:00 app[web.1]: +       div_main
2020-04-08T13:38:18.676902+00:00 app[web.1]: +     ),
2020-04-08T13:38:18.676940+00:00 app[web.1]: +     style = list('display' = 'flex',
2020-04-08T13:38:18.676988+00:00 app[web.1]: +                  'justify-content'='space-around')
2020-04-08T13:38:18.677036+00:00 app[web.1]: +   )
2020-04-08T13:38:18.677083+00:00 app[web.1]: + )
2020-04-08T13:38:18.770329+00:00 app[web.1]: >
2020-04-08T13:38:18.770330+00:00 app[web.1]: >
2020-04-08T13:38:18.770336+00:00 app[web.1]: > ## APP CALLBACKS
2020-04-08T13:38:18.770337+00:00 app[web.1]: >
2020-04-08T13:38:18.770337+00:00 app[web.1]: > # BOXPLOT (PLOT 1) & DROPDOWN
2020-04-08T13:38:18.770338+00:00 app[web.1]: > app$callback(
2020-04-08T13:38:18.770372+00:00 app[web.1]: +   output=list(id='Violin', property='figure'),
2020-04-08T13:38:18.770406+00:00 app[web.1]: +   params=list(input(id='Dropdown', property='value')),
2020-04-08T13:38:18.770428+00:00 app[web.1]: +   function(xaxis) {
2020-04-08T13:38:18.770460+00:00 app[web.1]: +     make_plot1(xaxis)
2020-04-08T13:38:18.770495+00:00 app[web.1]: +   })
2020-04-08T13:38:18.772953+00:00 app[web.1]: >
2020-04-08T13:38:18.772956+00:00 app[web.1]: > # HISTOGRAM (PLOT 2) & SLIDER
2020-04-08T13:38:18.772963+00:00 app[web.1]: > app$callback(
2020-04-08T13:38:18.772964+00:00 app[web.1]: +   output=list(id='Boxplot', property='figure'),
2020-04-08T13:38:18.772991+00:00 app[web.1]: +   params=list(input(id="Dropdown1", property='value')),
2020-04-08T13:38:18.773019+00:00 app[web.1]: +   function(xaxis) {
2020-04-08T13:38:18.773051+00:00 app[web.1]: +     make_plot2(xaxis)
2020-04-08T13:38:18.773085+00:00 app[web.1]: +   })
2020-04-08T13:38:18.786728+00:00 app[web.1]: >
2020-04-08T13:38:18.786733+00:00 app[web.1]: > ## Run app
2020-04-08T13:38:18.786734+00:00 app[web.1]: > app$run_server(debug=TRUE)
2020-04-08T13:38:18.787701+00:00 app[web.1]: ⚠ No source directory information available; hot reloading has been disabled.
2020-04-08T13:38:18.787701+00:00 app[web.1]: Please ensure that you are loading your Dash for R application using source().
2020-04-08T13:38:18.787702+00:00 app[web.1]:
2020-04-08T13:38:18.809496+00:00 app[web.1]: Fire started at 127.0.0.1:44548
2020-04-08T13:38:19.883416+00:00 app[web.1]: start: 127.0.0.1:44548
2020-04-08T13:39:13.414509+00:00 heroku[web.1]: State changed from starting to crashed
2020-04-08T13:39:29.105309+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=suicidesgroup13.herokuapp.com request_id=3df8575e-f5fd-40c3-8cbc-7d4c5b2c3145 fwd="76.64.227.44" dyno= connect= service= status=503 bytes= protocol=https
2020-04-08T13:39:29.843264+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=suicidesgroup13.herokuapp.com request_id=14fdb13f-df39-4167-8337-c42664a01ad3 fwd="76.64.227.44" dyno= connect= service= status=503 bytes= protocol=https
```

Do you know what the errors at the bottom mean, and how I may fix it?

Thanks!
Racquelle

**Comment by matthewconnell** [comment] 2020-04-08 19:09
Hi Racquelle,

I forked your repo and was able to reproduce the error. I changed the last line on your `app.R` file to `app$run_server(host = "0.0.0.0", port = Sys.getenv('PORT', 8050))` and was able to get it to deploy on heroku: https://group13-12121.herokuapp.com/

As you can see there is still some other problem going on with the plots, but I have the same issue when I run the app locally.

**Comment by yuliaUU** [comment] 2020-04-08 20:16
@matthewconnell when I open it, all runs well, don't see any issues with plots. Which browser you use?

**Comment by matthewconnell** [comment] 2020-04-08 20:21
Ah okay, it seems like it was a Firefox issue. I tried it with Chrome and it works fine.

Screenshot: 

Chrome | Firefox

<img width="1439" alt="Screen Shot 2020-04-08 at 1 19 55 PM" src="https://user-images.githubusercontent.com/29306639/78829809-dc3b7f80-799b-11ea-9081-2224145dcc72.png">

**Comment by yuliaUU** [comment] 2020-04-08 20:22
so weird, right??? I wonder why?

**Comment by matthewconnell** [comment] 2020-04-08 20:25
@racquellem Sorry for misleading you about the plots. Is everything working on your end?

**Comment by racquellem** [comment] 2020-04-08 21:19
Hi @matthewconnell, thanks for the help! I made the changes and I'm redoing the deployment again. The app is still being built in heroku (it is taking an extremely long time), but I will let you know if I encounter any additional problems.

**Closed** 2020-04-11 14:32 UTC
